spring:
  application:
    name: ConfigServerApp
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/manjunath1718/CricBuzzApp
          clone-on-start: true
          tryMasterBranch: false
          default-label: main
